import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import NavBar from "../components/navbar";
import Footer from "../components/footer";
import Explorehero from "../components/explorehero";
import Link from "next/link";
import CreateHero from "../components/createhero";

export default function Home() {
  const [navbar, setNavbar] = useState(false);
  return (
    <div className="bg-[#152022]  ">
      <Head>
        <title>Bunana-Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="Logo.svg" />
      </Head>

      {/* navbar start */}
      <div>
        {" "}
        <NavBar />
      </div>
      {/* nav bar end */}

      <main>
        <CreateHero />
      </main>

      {/* <Footer /> */}
    </div>
  );
}
