import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import NavBar from '../components/navbar';
import Hero from '../components/hero';
import Categ from '../components/categories';
import Trending from '../components/trending';
import Carousel from '../components/carousel';
import Footer from '../components/footer';
import Soicials from '../components/socials';
import Link from 'next/link';


export default function Home() {
  const [navbar, setNavbar] = useState(false);
  return (
    <div className="bg-[#152022] scrollbar-hide">
      <Head>
        <title>BunanA-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="Logo.svg" />
      </Head>

      {/* navbar start */}
      <div > <NavBar/> </div>
      {/* nav bar end */}

      <main >
        <Hero/>
        <Trending/>
        <Carousel/>
        <Categ/>
      


      </main>


      <Soicials/>
      
      <Footer/>
     
    </div>
  )
}
